### ISSUE TITLE
Race condition in channel send/recv

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#191]
Reproduction:

```
for i in `seq 1 1000`; do cargo test --test stream || break; done
```

One stack trace:

```
---- or_else stdout ----
        thread 'or_else' panicked at 'on_full interference', ../src/libcore/option.rs:705
stack backtrace:
   1:     0x55f68ecde31f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x55f68ece250d - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x55f68ece12ce - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x55f68ece19b8 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x55f68ece1852 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x55f68ece1790 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x55f68ece1711 - rust_begin_unwind
   8:     0x55f68ed1b79f - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x55f68ed1b815 - core::option::expect_failed::hafc66854f3459293
  10:     0x55f68ec2be61 - <core::option::Option<T>>::expect::h206f4be7dcade172
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:293
  11:     0x55f68ec26de0 - <futures::slot::Slot<T>>::on_full::hf0de72bb4837a7e0
                        at /home/alex/code/futures/src/slot.rs:342
  12:     0x55f68ec8aaa8 - <futures::stream::channel::Receiver<T, E> as futures::stream::Stream>::poll::h46de1793c45248df
                        at /home/alex/code/futures/src/stream/channel.rs:116
  13:     0x55f68ec1b6f7 - <futures::stream::or_else::OrElse<S, F, U> as futures::stream::Stream>::poll::h9c31f7f1c130f6ec
                        at /home/alex/code/futures/src/stream/or_else.rs:39
  14:     0x55f68ec71c27 - <futures::stream::collect::Collect<S> as futures::Future>::poll::hdfeaa374f77c0aa9
                        at /home/alex/code/futures/src/stream/collect.rs:40
  15:     0x55f68ec94a6b - <futures::task::Spawn<F>>::poll_future::{{closure}}::h135027c8b3b88cb6
                        at /home/alex/code/futures/src/task/mod.rs:217
  16:     0x55f68ec950ad - <futures::task::Spawn<T>>::enter::{{closure}}::h672c1c21a71f3f88
                        at /home/alex/code/futures/src/task/mod.rs:304
  17:     0x55f68ec995dd - futures::task::set::{{closure}}::hb56804eeda12565a
                        at /home/alex/code/futures/src/task/mod.rs:75
  18:     0x55f68ec4bfcc - <std::thread::local::LocalKey<T>>::with::hccadf02167c9cb77
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
  19:     0x55f68ec74059 - futures::task::set::hc014cf74b6134a1e
                        at /home/alex/code/futures/src/task/mod.rs:72
  20:     0x55f68ec3ab56 - <futures::task::Spawn<T>>::enter::h312d0bf1a006dd24
                        at /home/alex/code/futures/src/task/mod.rs:304
  21:     0x55f68ec30739 - <futures::task::Spawn<F>>::poll_future::ha6f9333bb20e85f1
                        at /home/alex/code/futures/src/task/mod.rs:217
  22:     0x55f68ec35a9a - <futures::task::Spawn<F>>::wait_future::hb402901aab6f5ae1
                        at /home/alex/code/futures/src/task/mod.rs:229
  23:     0x55f68ec7755a - futures::Future::wait::h25c2e8f749455124
                        at /home/alex/code/futures/src/lib.rs:387
  24:     0x55f68ec8e283 - stream::support::assert_done::hd1e1bf8df99f6f74
                        at /home/alex/code/futures/tests/support/mod.rs:22
  25:     0x55f68ec8f742 - stream::or_else::h921dfef85323b046
                        at /home/alex/code/futures/tests/stream.rs:76
  26:     0x55f68eca5eeb - <F as alloc::boxed::FnBox<A>>::call_box::hdb02e989a089cf4e
  27:     0x55f68ec9fd03 - std::panicking::try::do_call::hb5542e7f62c71bb7
  28:     0x55f68ece9fd6 - __rust_maybe_catch_panic
  29:     0x55f68eca5d59 - <F as alloc::boxed::FnBox<A>>::call_box::hb415bac963aa88f8
  30:     0x55f68ece0190 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  31:     0x7fc62397a6f9 - start_thread
  32:     0x7fc62349ab5c - clone
  33:                0x0 - <unknown>
```

**Comment by tmiasko** [comment]
With spurious wakeups, following scenario is possible:

```
R: Slot::on_full
R:   stores on_full callback
R:   publishes callback with ON_FULL flag

S: Slot::try_produce
S:   stores data in slot
S:   publishes data with DATA flag, removes ON_FULL flag
S:   tries to lock on_full

R: Slot::cancel
R:   ON_FULL is no longer set, returns early
R: Slot::try_consume
R:   consumes data from slot
R:   removes DATA flag
R: Slot::try_consume
R:   no DATA flag, returns
R: Slot::on_full
R:   tries to lock on_full
```

**Comment by alexcrichton** [comment]
Unfortunately yeah the current design is basically just fundamentally flawed. The `Slot` type also dates *long* ago to a point where callbacks were much heavier, and it's not really pulling its weight today (unnecessarily costly).

I already rewrote the `Oneshot` type to [not use `Slot`](https://github.com/alexcrichton/futures-rs/commit/2ece87ddeb372b384c9a29012fa77851123e085d) and I plan on doing so for `channel` shortly, resolving this race in the meantime.

**Comment by alexcrichton** [comment]
Ok, I've got a rewritten implementation over at https://github.com/alexcrichton/futures-rs/pull/215

**Comment by tmiasko** [comment]
With a new channel implementation I still experience interferences when running tests.
In particular the Receiver taking the data in Drop panicks. For example:

```
test and_then ... FAILED

failures:

---- and_then stdout ----
	thread 'and_then' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x55d5ede8be0f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x55d5ede8fffd - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x55d5ede8edbe - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x55d5ede8f4a8 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x55d5ede8f342 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x55d5ede8f280 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x55d5ede8f201 - rust_begin_unwind
   8:     0x55d5edec92cf - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x55d5edec91fb - core::panicking::panic::h1a2d1a6b50eaa468
  10:     0x55d5eddd3901 - <core::option::Option<T>>::unwrap::hab93c207686a822d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
  11:     0x55d5ede2d04c - <futures::stream::channel::Receiver<T, E> as core::ops::Drop>::drop::hbee5d54e7317f335
                        at .../futures-rs/src/stream/channel.rs:284
  12:     0x55d5ede024e0 - drop::h53b7c14df5dafcda
  13:     0x55d5ede046a8 - drop::heb5674278121d104
  14:     0x55d5ede021e0 - drop::h4cc1eda715ec8b4f
  15:     0x55d5ede02530 - drop::h542c89df12406662
  16:     0x55d5ede1e286 - futures::Future::wait::h06e31fa5ebf73ce7
                        at .../futures-rs/src/lib.rs:389
  17:     0x55d5ede36e63 - stream::support::assert_done::h0359280c60ca4bc2
                        at .../futures-rs/tests/support/mod.rs:22
  18:     0x55d5ede3b283 - stream::and_then::h3b3e99a1b47ff71a
                        at .../futures-rs/tests/stream.rs:65
  19:     0x55d5ede53a5b - <F as alloc::boxed::FnBox<A>>::call_box::hdb02e989a089cf4e
  20:     0x55d5ede4db07 - std::panicking::try::do_call::hb5542e7f62c71bb7
  21:     0x55d5ede97ac6 - __rust_maybe_catch_panic
  22:     0x55d5ede538c9 - <F as alloc::boxed::FnBox<A>>::call_box::hb415bac963aa88f8
  23:     0x55d5ede8dc80 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  24:     0x7f438ae0e463 - start_thread
  25:     0x7f438a93a9de - __clone
  26:                0x0 - <unknown>
  ```

BTW panics from thread created inside forget are ignored, so it is easy to miss some problems.

**Comment by alexcrichton** [comment]
Thanks for the sharp eye @tmiasko! I think I've addressed that in https://github.com/alexcrichton/futures-rs/commit/6cefd738b12bfd6cc224ab7a40d0a41525fa6914
