### ISSUE TITLE
`and_then` may poll `FutureResult` twice

### ISSUE THREAD

**Issue by valarauca** [alexcrichton/futures-rs#636]
I cannot reliably recreate this.

But a very rare failure mode I've seen in prod is

```
 thread 'main' panicked at 'cannot poll Result twice', /checkout/src/libcore/option.rs:839:4
 stack backtrace:
    0:     0x56364ac0adf3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1070d2fb95184fa2
                                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1:     0x56364ac08906 - std::panicking::default_hook::{{closure}}::hd87027f00dc92814
                                at /checkout/src/libstd/sys_common/backtrace.rs:69
                                at /checkout/src/libstd/sys_common/backtrace.rs:58
                                at /checkout/src/libstd/panicking.rs:381
    2:     0x56364ac07ce9 - std::panicking::rust_panic_with_hook::h97def5bc16cf8ad9
                                at /checkout/src/libstd/panicking.rs:397
                                at /checkout/src/libstd/panicking.rs:577
    3:     0x56364ac0777e - std::panicking::begin_panic::hd4ff6c8c17230ea6
                                at /checkout/src/libstd/panicking.rs:538
    4:     0x56364ac076f9 - std::panicking::begin_panic_fmt::h2da9e717417b9bee
                                at /checkout/src/libstd/panicking.rs:522
    5:     0x56364ac1a888 - core::panicking::panic_fmt::h5fee652e7adf46a7
                                at /checkout/src/libstd/panicking.rs:498
    6:     0x56364ac2099d - core::option::expect_failed::h613f7eb071244145
                                at /checkout/src/libcore/option.rs:839
    7:     0x56364aa288fa - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h262f8c0d5f4b4ae4
                                at /checkout/src/libcore/option.rs:302
                                at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/result.rs:73
                                at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:32
                                at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
    8:     0x56364a98ec77 - <futures::future::map::Map<A, F> as futures::future::Future>::poll::he3c440e34bfaabd5
```

This is happening within a `futures-cpupool` higher in the stack.

**Comment by carllerche** [comment]
It looks like to me that `and_then` will double poll the second future if it is itself double polled.

This would imply that the issue is higher up in the future chain (not and_then).
